language: ruby
cache: bundler
bundler_args: --without production
deploy:
  provider: heroku
  api_key:
    secure: JhKSI3OqjpKhBZ7NKIuauQz468UxuGrRJQL4wXCaYkgbppgc85dUPPKK0FRmOSX+Fe9fLbOP4acCgcr6GpIaOcccjVKYbUAMV41b3yi6X39oBs96zMYPQmBvnKYYYiBhn6YpM/9KQ0L5W0C9LT81srttOb4oBvYKP3PE5FwYjuRiFQKs6jEBXb8oSE4fwFDNcHRK48bWN23pKSKdBJZv9oIumWYvKkhtpMcc92yjMAAQ7nDnLSZiiAvdSiQ8pMP2zyRtu1WZdGXEFx5JQF6BQKg4wwB1PzO0E9hjYgQz7EA2vOyBSHsSXSSbMB5h63ZlH46R/cjWKwiMF/ejvKBsJ2vTxBOGMGH8xWi/C3iq75VYbAXXIkXPiU8zorguBH0a/E34+iQ17rMBO1yul+YxgxA6ZxNuumE+h6VOsCxFa3yGkCT/1wXlf6tKEtMxsEgUdg4ldNewInpX+dS+ojR/KvW97CWo09u+3V3NaN9fO261pljCgqgmi83zw0vKwh9a/O5Caa3tyvlDCVHxPZOTI5GdCRsaQgu6cPQJtouQjlhF0l7muSNnMAsTr5r1T1A/Z27qPBQukank+ebwlRa4shGTxMCf4dqI8jtFEIbwuVOcG6w9Jo4G9qtr3VQFA0W82JtcZbwpwLElxHY1ywV5Yc8h3Zm/UgB47/HdjS+iq2Q=
  on:
    branch: master
