language: ruby
cache: bundler
bundler_args: "--without production"
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: FFl4dYFs87OKZSbzmN0Hk90L3VjHNDGwZ9t5UpjwslP1DQLZ/VuW0PRw7IcZybH2kpJr/z5q0Pq537s/G1dxuUqVZFcSEF40tFJi5A7CKr27zLdMnzJpynkEJVJQerilh2TIGnjB6jMz1GDLhTa5N9Ip74O+Kn3ul7doKte0CRVMvynNCSijw69F6PjLiyrsswq/XIt+dw0qcR2M+p5pWXT6wyjir8boCaskCOT6k0Ry5LtqLtXLCv20CnI229ReMyz+q3vRYOPrTWKEAIYufQPAuriqOg+n9J0DAW3UR+vPgueoW5i1Ia4A0tCT1QcBUCeIaiRXopnHweS6Q+FZhMyu8z51g2rrWxqAq3rc6TLN+LqhC2q96XhAKPIai7u/xtF1GftjFmN0emVc0XbRevaCa5OBQAJdbWd0B/GlfzH4bw8i2lLOGS32AzGcPjyFMHPEdMcJFDgzhZ0Ezjtu2DGshdM332lyEeLPGofb37akupkd/a4LszadTVKYoOVF+OvtRRjsTzTcWtfNDDIiIz5OZRGNLKIuyTyPcNRQ/VMchnKPeUnUTd+0p8+7bCT3+KDQRsfHXqpFRKpJS3Ig1ojORgbzMIyjfB9gjoVAER6LWyNB82mYCMWXeLnwRZeLy3JFRE8SOxEc0Fssfo1m9C1JKUyKYMLZEnli1KdjOmE=
  on:
    branch: master
