language: ruby
cache: bundler
bundler_args: "--without production"
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: HpF3sgKVfq0BEbQnAvZUWC8e/HCWgW8PVi+uthxDdQ6Cw95zxsG8zPW3bs4ZnmyTU8b8i+g5Xzgf8XyoJfDWFqlWy7Ukfffo6anytbm0fVv6f5MBhLnH4u2C6NZkMI37jucH9Vyna65ZZxht32LofQxineVyF6XIpJJu/kdSkTGXVXvbnTBNH6dNF5qI4vzOGP+rGt7MAGAW6Nna5Jp1NORUwaRWBP5sblTpuFAW1h8xssYWfhEg46XvNzLLgBSyauz0VYtMOD9Xho3C5hTDjFGKMOHfuHgS5VG/5257kKqezpfx6DTXKrHDCk+DI7BY3ICA5gCyGeYgjuch5IVUmeStEdP3QinESS43KMaWXigdp+9x2ccFtqm7QobDCLQG1Wr1vOZhpF0kmkRAKrSPor/gfY5ffuDR/X1jT+v/uQyMHxTZxD0M9f133x9lpylQSy42BfeLKYRfGDk/i6f0741SA3Qi4TFnU4Tq5OMAy6xbUzqq/254UeBIb5unvjonXIu8NPEcBSwpTKif1+C62QWDbj83axuXfXsJtqEnJo1w89MKiWrHzRcxsb//EQvEe3Gfarw6gIYIMc66CselrFhT8tFDTnuNesSdcfD6ro65+dSmYdL/h3+ILsEcaD0ff50v27gUyG3JKtQphqV1ZQJ6nYpkWvFB2Pt3Oi6rdw8=
  on:
    branch: master
